[versions]
aboutlib_version = "10.10.0"
accompanist = "0.34.0"
activity = "1.8.2"
adaptiveiconview = "v0.0.3"
agp = "8.2.2"
appcompat = "1.6.1"
cardview = "1.0.0"
coil = "2.5.0"
compose = "1.6.0"
compose-material3 = "1.2.0-rc01"
core-ktx = "1.12.0"
dagger = "2.50"
expandabletextcompose = "2.0.0"
gms-location = "21.1.0"
hilt = "1.1.0"
jjwt = "0.12.5"
junit = "5.10.1"
kotest-assertions = "5.8.0"
kotlin = "1.9.22"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.6.2"
kotlinx-serialization-retrofitconverter = "1.0.0"
lifecycle = "2.7.0"
lifecycle-extensions = "2.2.0"
lunarcalendar = "4.0.7"
material = "1.11.0"
mockk = "1.13.9"
navigation-compose = "2.7.6"
objectbox = "3.7.1"
okhttp = "4.12.0"
preference-ktx = "1.2.1"
recyclerview = "1.3.2"
retrofit = "2.9.0"
rxandroid = "3.0.2"
rxjava = "3.1.8"
suncalc = "2.14"
swiperefreshlayout = "1.1.0"
work-runtime = "2.9.0"

[libraries]
aboutLibraries = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlib_version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
adaptiveiconview = { group = "com.github.breezy-weather", name = "AdaptiveIconView", version.ref = "adaptiveiconview" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple", version.ref = "compose" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
expandabletextcompose = { group = "com.github.giangpham96.expandable-text", name = "expandable_text_compose", version.ref = "expandabletextcompose" }
gms-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "gms-location" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-orgjson = { group = "io.jsonwebtoken", name = "jjwt-orgjson", version.ref = "jjwt" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest-assertions" }
kotlinx-coroutines-rx3 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-retrofitconverter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-retrofitconverter" }
lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-reactivestreams-ktx = { group = "androidx.lifecycle", name = "lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lunarcalendar = { group = "com.xhinliang", name = "LunarCalendar", version.ref = "lunarcalendar" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
objectbox-android = { group = "io.objectbox", name = "objectbox-android", version.ref = "objectbox" }
objectbox-androidobjectbrowser = { group = "io.objectbox", name = "objectbox-android-objectbrowser", version.ref = "objectbox" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
retrofit-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
suncalc = { group = "org.shredzone.commons", name = "commons-suncalc", version.ref = "suncalc" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work-runtime" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlib_version" }
daggerHilt = { id = "dagger.hilt.android.plugin", version.ref = "dagger" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
objectbox = { id = "io.objectbox", version.ref = "objectbox" }

[bundles]
lifecycle = ["lifecycle-common-java8", "lifecycle-extensions", "lifecycle-livedata-ktx", "lifecycle-reactivestreams-ktx", "lifecycle-runtime-ktx", "lifecycle-viewmodel-compose", "lifecycle-viewmodel-ktx"]
okhttp = ["okhttp-core", "okhttp-logging"]
retrofit = ["retrofit-adapter-rxjava3", "retrofit-core"]
test = ["junit", "kotest-assertions", "kotlinx-coroutines-test", "mockk"]