[versions]
aboutlib_version = "11.2.3"
accompanist = "0.34.0"
activity = "1.9.1"
adaptiveiconview = "v0.0.3"
agp = "8.6.0"
appcompat = "1.7.0"
cardview = "1.0.0"
compose = "1.6.8"
compose-lint-checks = "1.3.1"
compose-material3 = "1.2.1"
core-ktx = "1.13.1"
dagger = "2.52"
datastore = "1.1.1"
expandabletextcompose = "2.0.1"
hilt = "1.2.0"
javapoet = "1.13.0"
jjwt = "0.12.6"
junit = "5.11.0"
kotest-assertions = "5.9.1"
kotlin = "2.0.20"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization-json = "1.7.1"
kotlinx-serialization-xml = "3980721899b8a990d9e5df170459e17b81fbc34d"
ktlint = "12.1.1"
leakcanary = "2.14"
lifecycle = "2.8.4"
lifecycle-extensions = "2.2.0"
material = "1.12.0"
mockk = "1.13.12"
navigation-compose = "2.7.7"
okhttp = "4.12.0"
preference-ktx = "1.2.1"
recyclerview = "1.3.2"
restrictionBypass = "2.2"
retrofit = "2.11.0"
rxandroid = "3.0.2"
rxjava = "3.1.9"
sqldelight = "2.0.2"
sqlite = "3.45.0"
sqlite-android = "2.4.0"
suncalc = "2.14"
swiperefreshlayout = "1.1.0"
vico = "2.0.0-alpha.28"
work-runtime = "2.9.1"

[libraries]
aboutLibraries = { group = "com.mikepenz", name = "aboutlibraries-compose-m3", version.ref = "aboutlib_version" }
aboutLibraries-gradle = { group = "com.mikepenz.aboutlibraries.plugin", name = "aboutlibraries-plugin", version.ref = "aboutlib_version" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
adaptiveiconview = { group = "com.github.breezy-weather", name = "AdaptiveIconView", version.ref = "adaptiveiconview" }
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-lint-checks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "compose-lint-checks" }
compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple", version.ref = "compose" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-gradle = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
expandabletextcompose = { group = "com.github.giangpham96.expandable-text", name = "expandable_text_compose", version.ref = "expandabletextcompose" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-orgjson = { group = "io.jsonwebtoken", name = "jjwt-orgjson", version.ref = "jjwt" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest-assertions" }
kotlinx-coroutines-rx3 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-xml = { group = "com.github.rharter", name = "kotlinx-serialization-xml", version.ref = "kotlinx-serialization-xml" }
ktlint = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlint" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-reactivestreams-ktx = { group = "androidx.lifecycle", name = "lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
restrictionBypass = { group = "com.github.ChickenHook", name = "RestrictionBypass", version.ref = "restrictionBypass" }
retrofit-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-android-paging = { group = "app.cash.sqldelight", name = "androidx-paging3-extensions", version.ref = "sqldelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions-jvm", version.ref = "sqldelight" }
sqldelight-dialects-sql = { group = "app.cash.sqldelight", name = "sqlite-3-38-dialect", version.ref = "sqldelight" }
sqldelight-gradle = { group = "app.cash.sqldelight", name = "gradle-plugin", version.ref = "sqldelight" }
sqlite-android = { group = "com.github.requery", name = "sqlite-android", version.ref = "sqlite" }
sqlite-framework = { group = "androidx.sqlite", name = "sqlite-framework", version.ref = "sqlite-android" }
sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqlite-android" }
suncalc = { group = "org.shredzone.commons", name = "commons-suncalc", version.ref = "suncalc" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work-runtime" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
lifecycle = ["lifecycle-common-java8", "lifecycle-extensions", "lifecycle-livedata-ktx", "lifecycle-reactivestreams-ktx", "lifecycle-runtime-ktx", "lifecycle-viewmodel-compose", "lifecycle-viewmodel-ktx"]
okhttp = ["okhttp-core", "okhttp-logging", "okhttp-tls"]
retrofit = ["retrofit-adapter-rxjava3", "retrofit-converter-kotlinx-serialization", "retrofit-core"]
sqldelight = ["sqldelight-android-driver", "sqldelight-coroutines", "sqldelight-android-paging"]
sqlite = ["sqlite-framework", "sqlite-ktx", "sqlite-android"]
test = ["junit", "kotest-assertions", "kotlinx-coroutines-test", "mockk"]
