name: Breezy Weather Pull Request CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - ".editorconfig"
      - "docs/*"
      - "fastlane/*"
      - "work/*"
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Dependency review
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - name: Lint
        run: ./gradlew spotlessCheck

      - name: Clean build
        run: ./gradlew clean

      - name: Assemble basic flavor
        run: ./gradlew assembleBasicDebug

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: BreezyWeather_basicDebug.apk
          path: app/build/outputs/apk/basic/debug/app-basic-universal-debug.apk
