name: Breezy Weather Pull Request CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - ".editorconfig"
      - "docs/*"
      - "fastlane/*"
      - "work/*"
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Dependency review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1

      - name: Lint
        run: ./gradlew spotlessCheck

      - name: Clean build
        run: ./gradlew clean

      - name: Assemble basic flavor
        run: ./gradlew assembleBasicDebug

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: BreezyWeather_basicDebug.apk
          path: app/build/outputs/apk/basic/debug/app-basic-universal-debug.apk
