name: Breezy Weather Pull Request CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - ".editorconfig"
      - "docs/*"
      - "fastlane/*"
      - "work/*"
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint + Assemble basic flavor
        run: ./gradlew spotlessCheck assembleBasicDebug

      - uses: actions/upload-artifact@v4
        with:
          name: BreezyWeather_basicDebug.apk
          path: app/build/outputs/apk/basic/debug/app-basic-universal-debug.apk
