name: Breezy Weather push CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Add secrets to local.properties
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          echo "breezy.source.default_weather=accu" >> local.properties
          echo "breezy.accu.key=$ACCU_WEATHER_KEY" >> local.properties
          echo "breezy.atmoaura.key=$ATMO_AURA_KEY" >> local.properties
          echo "breezy.baiduip.key=$BAIDU_IP_LOCATION_AK" >> local.properties
          echo "breezy.geonames.key=$GEO_NAMES_KEY" >> local.properties
          echo "breezy.mf.jwtKey=$MF_WSFT_JWT_KEY" >> local.properties
          echo "breezy.mf.key=$MF_WSFT_KEY" >> local.properties
          echo "breezy.openweather.key=$OPEN_WEATHER_KEY" >> local.properties
        env:
          ACCU_WEATHER_KEY: ${{ secrets.ACCU_WEATHER_KEY }}
          ATMO_AURA_KEY: ${{ secrets.ATMO_AURA_KEY }}
          BAIDU_IP_LOCATION_AK: ${{ secrets.BAIDU_IP_LOCATION_AK }}
          GEO_NAMES_KEY: ${{ secrets.GEO_NAMES_KEY }}
          MF_WSFT_JWT_KEY: ${{ secrets.MF_WSFT_JWT_KEY }}
          MF_WSFT_KEY: ${{ secrets.MF_WSFT_KEY }}
          OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleStandardRelease

      - name: Delete local.properties
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          rm local.properties

      - name: Save version tag in env
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Prepare APKs with checksums, archive mapping.txt file
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk breezy-weather-${{ env.VERSION_TAG }}.apk
          sha256=`sha256sum breezy-weather-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk breezy-weather-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha256=`sha256sum breezy-weather-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk breezy-weather-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha256=`sha256sum breezy-weather-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned-signed.apk breezy-weather-x86-${{ env.VERSION_TAG }}.apk
          sha256=`sha256sum breezy-weather-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned-signed.apk breezy-weather-x86_64-${{ env.VERSION_TAG }}.apk
          sha256=`sha256sum breezy-weather-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA256=$sha256" >> $GITHUB_ENV
          tar -czvf mapping-${{ env.VERSION_TAG }}.tar.gz --directory=app/build/outputs/mapping/standardRelease/ mapping.txt

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Breezy Weather ${{ env.VERSION_TAG }}
          body: |
            *Releases distributed on GitHub do not include proprietary Network Location Providers*

            ---

            ### Checksums
            | Variant     | SHA-256                           |
            |-------------|-----------------------------------|
            | Universal   | ${{ env.APK_UNIVERSAL_SHA256 }}   |
            | arm64-v8a   | ${{ env.APK_ARM64_V8A_SHA256 }}   |
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA256 }} |
            | x86         | ${{ env.APK_X86_SHA256 }}         |
            | x86_64      | ${{ env.APK_X86_64_SHA256 }}      |
          files: |
            breezy-weather-${{ env.VERSION_TAG }}.apk
            breezy-weather-arm64-v8a-${{ env.VERSION_TAG }}.apk
            breezy-weather-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            breezy-weather-x86-${{ env.VERSION_TAG }}.apk
            breezy-weather-x86_64-${{ env.VERSION_TAG }}.apk
            mapping-${{ env.VERSION_TAG }}.tar.gz
          draft: true
          prerelease: false