name: Breezy Weather push CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleFdroidRelease

      - name: Add secrets to local.properties
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          echo "breezy.accu.key=$ACCU_WEATHER_KEY" >> local.properties
          echo "breezy.atmoaura.key=$ATMO_AURA_KEY" >> local.properties
          echo "breezy.baiduip.key=$BAIDU_IP_LOCATION_AK" >> local.properties
          echo "breezy.geonames.key=$GEO_NAMES_KEY" >> local.properties
          echo "breezy.mf.jwtKey=$MF_WSFT_JWT_KEY" >> local.properties
          echo "breezy.mf.key=$MF_WSFT_KEY" >> local.properties
          echo "breezy.openweather.key=$OPEN_WEATHER_KEY" >> local.properties
        env:
          ACCU_WEATHER_KEY: ${{ secrets.ACCU_WEATHER_KEY }}
          ATMO_AURA_KEY: ${{ secrets.ATMO_AURA_KEY }}
          BAIDU_IP_LOCATION_AK: ${{ secrets.BAIDU_IP_LOCATION_AK }}
          GEO_NAMES_KEY: ${{ secrets.GEO_NAMES_KEY }}
          MF_WSFT_JWT_KEY: ${{ secrets.MF_WSFT_JWT_KEY }}
          MF_WSFT_KEY: ${{ secrets.MF_WSFT_KEY }}
          OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleBasicRelease

      - name: Add default location source for gplay flavor
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          echo "breezy.source.default_location=googlefused" >> local.properties

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleGplayRelease

      - name: Delete local.properties
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          rm local.properties

      - name: Save version tag in env
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK (F-Droid)
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/fdroid/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign APK (basic)
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/basic/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign APK (gplay)
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/gplay/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Prepare APKs with checksums, archive mapping.txt file
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        run: |
          set -e
          mv app/build/outputs/apk/basic/release/app-basic-universal-release-unsigned-signed.apk breezy-weather-${{ env.VERSION_TAG }}_standard.apk
          sha256=`sha256sum breezy-weather-${{ env.VERSION_TAG }}_standard.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/basic/release/app-basic-arm64-v8a-release-unsigned-signed.apk breezy-weather-arm64-v8a-${{ env.VERSION_TAG }}_standard.apk
          sha256=`sha256sum breezy-weather-arm64-v8a-${{ env.VERSION_TAG }}_standard.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/basic/release/app-basic-armeabi-v7a-release-unsigned-signed.apk breezy-weather-armeabi-v7a-${{ env.VERSION_TAG }}_standard.apk
          sha256=`sha256sum breezy-weather-armeabi-v7a-${{ env.VERSION_TAG }}_standard.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/basic/release/app-basic-x86-release-unsigned-signed.apk breezy-weather-x86-${{ env.VERSION_TAG }}_standard.apk
          sha256=`sha256sum breezy-weather-x86-${{ env.VERSION_TAG }}_standard.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/basic/release/app-basic-x86_64-release-unsigned-signed.apk breezy-weather-x86_64-${{ env.VERSION_TAG }}_standard.apk
          sha256=`sha256sum breezy-weather-x86_64-${{ env.VERSION_TAG }}_standard.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/gplay/release/app-gplay-universal-release-unsigned-signed.apk breezy-weather-${{ env.VERSION_TAG }}_gplay.apk
          sha256=`sha256sum breezy-weather-${{ env.VERSION_TAG }}_gplay.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_GPLAY_SHA256=$sha256" >> $GITHUB_ENV
          mv app/build/outputs/apk/fdroid/release/app-fdroid-universal-release-unsigned-signed.apk breezy-weather-${{ env.VERSION_TAG }}_fdroid.apk
          sha256=`sha256sum breezy-weather-${{ env.VERSION_TAG }}_fdroid.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_FDROID_SHA256=$sha256" >> $GITHUB_ENV
          tar -czvf mapping-${{ env.VERSION_TAG }}_standard.tar.gz --directory=app/build/outputs/mapping/basicRelease/ mapping.txt
          tar -czvf mapping-${{ env.VERSION_TAG }}_fdroid.tar.gz --directory=app/build/outputs/mapping/fdroidRelease/ mapping.txt
          tar -czvf mapping-${{ env.VERSION_TAG }}_gplay.tar.gz --directory=app/build/outputs/mapping/gplayRelease/ mapping.txt

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Breezy Weather ${{ env.VERSION_TAG }}
          body: |
            **Donâ€™t know which release to choose? Check [INSTALL instructions](https://github.com/breezy-weather/breezy-weather/blob/main/INSTALL.md).**

            ---

            ### Checksums
            | Flavor      | Variant     | SHA-256                                |
            |-------------|-------------|----------------------------------------|
            | Standard    | Universal   | ${{ env.APK_UNIVERSAL_SHA256 }}        |
            | Standard    | arm64-v8a   | ${{ env.APK_ARM64_V8A_SHA256 }}        |
            | Standard    | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA256 }}      |
            | Standard    | x86         | ${{ env.APK_X86_SHA256 }}              |
            | Standard    | x86_64      | ${{ env.APK_X86_64_SHA256 }}           |
            | Google Play | Universal   | ${{ env.APK_UNIVERSAL_GPLAY_SHA256 }}  |
            | F-Droid     | Universal   | ${{ env.APK_UNIVERSAL_FDROID_SHA256 }} |
          files: |
            breezy-weather-${{ env.VERSION_TAG }}_standard.apk
            breezy-weather-arm64-v8a-${{ env.VERSION_TAG }}_standard.apk
            breezy-weather-armeabi-v7a-${{ env.VERSION_TAG }}_standard.apk
            breezy-weather-x86-${{ env.VERSION_TAG }}_standard.apk
            breezy-weather-x86_64-${{ env.VERSION_TAG }}_standard.apk
            mapping-${{ env.VERSION_TAG }}_standard.tar.gz
            breezy-weather-${{ env.VERSION_TAG }}_gplay.apk
            mapping-${{ env.VERSION_TAG }}_gplay.tar.gz
            breezy-weather-${{ env.VERSION_TAG }}_fdroid.apk
            mapping-${{ env.VERSION_TAG }}_fdroid.tar.gz
          draft: true
          prerelease: false
